default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-docstring-first
        exclude: ^e2e_projects/
    -   id: check-json
    -   id: check-merge-conflict
        exclude: \.rst$
    -   id: check-yaml
    -   id: debug-statements
        exclude: tests/data/test_generation/invalid_syntax\.py
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
