default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-docstring-first
        exclude: ^e2e_projects/
    -   id: check-json
    -   id: check-merge-conflict
        exclude: \.rst$
    -   id: check-yaml
    -   id: debug-statements
        exclude: tests/data/test_generation/invalid_syntax\.py
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
    -   id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        args: [--config-file=mypy.ini]
        exclude: (tests/|docs/)
        additional_dependencies:
        -    click>=8.0.0
        -    coverage>=7.3.0
        -    libcst>=1.8.5
        -    pytest>=6.2.5
        -    setproctitle>=1.1.0
        -    textual>=1.0.0
        -    types-toml>=0.10.2
