version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install the package itself to build docs
python:
  install:
    - method: pip
      path: .


build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
