version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Install the package itself to build docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
